import 'package:flutter/material.dart';
import 'package:Memento/screens/home_screen/models/home_widget_size.dart';
import 'package:Memento/widgets/common/timeline_schedule_card.dart';

/// 时间线日程卡片示例
class TimelineScheduleCardExample extends StatelessWidget {
  const TimelineScheduleCardExample({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(title: const Text('时间线日程卡片')),
      body: Container(
        color: isDark ? Colors.black : const Color(0xFFF2F2F7),
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('小尺寸'),
                const SizedBox(height: 8),
                Center(
                  child: SizedBox(
                    width: 150,
                    height: 150,
                    child: TimelineScheduleCard(
                      size: const SmallSize(),
                      todayWeekday: 'Monday',
                      todayDay: 7,
                      tomorrowWeekday: 'Tuesday',
                      tomorrowDay: 8,
                      todayEvents: [
                        TimelineEvent(
                          hour: 10,
                          title: 'Farmers Market',
                          time: '9:45AM',
                          color: const Color(0xFFF3A541),
                          backgroundColorLight: const Color(0xFFFEF7EC),
                          backgroundColorDark: const Color(0xFF4A3816),
                          textColorLight: const Color(0xFF6B4916),
                          textColorDark: const Color(0xFFFFD699),
                          subtextLight: const Color(0xFFA68B4E),
                          subtextDark: const Color(0xFFC4A774),
                        ),
                        TimelineEvent(
                          hour: 11,
                          title: 'Weekly Prep',
                          time: '11:15AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 13,
                          title: 'Product Sprint',
                          time: '1PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Team Goals',
                          time: '3PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                      ],
                      tomorrowEvents: [
                        TimelineEvent(
                          hour: 9,
                          title: 'Team Goals',
                          time: '9AM',
                          color: const Color(0xFFEE4B55),
                          backgroundColorLight: const Color(0xFFFCECEC),
                          backgroundColorDark: const Color(0xFF4A1818),
                          textColorLight: const Color(0xFF5C1519),
                          textColorDark: const Color(0xFFF1A9A9),
                        ),
                        TimelineEvent(
                          hour: 10,
                          title: 'Design Review',
                          time: '10AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 14,
                          title: 'Team Lunch',
                          time: '2PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Regroup',
                          time: '3PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                        ),
                      ],
                      tomorrowSpecialEvent: SpecialEvent(
                        title: "Ravi's Birthday",
                        icon: Icons.card_giftcard,
                      ),
                      todayMoreEventsCount: 3,
                      todayMoreEventsColors: [
                        const Color(0xFFFED6A3),
                        const Color(0xFFF5B8C8),
                        const Color(0xFFA5D4F1),
                      ],
                      tomorrowMoreEventsCount: 2,
                      tomorrowMoreEventsColors: [
                        const Color(0xFFC4B5FD),
                        const Color(0xFFF9A8D4),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                _buildSectionTitle('中尺寸'),
                const SizedBox(height: 8),
                Center(
                  child: SizedBox(
                    width: 220,
                    height: 220,
                    child: TimelineScheduleCard(
                      size: const MediumSize(),
                      todayWeekday: 'Monday',
                      todayDay: 7,
                      tomorrowWeekday: 'Tuesday',
                      tomorrowDay: 8,
                      todayEvents: [
                        TimelineEvent(
                          hour: 10,
                          title: 'Farmers Market',
                          time: '9:45AM',
                          color: const Color(0xFFF3A541),
                          backgroundColorLight: const Color(0xFFFEF7EC),
                          backgroundColorDark: const Color(0xFF4A3816),
                          textColorLight: const Color(0xFF6B4916),
                          textColorDark: const Color(0xFFFFD699),
                          subtextLight: const Color(0xFFA68B4E),
                          subtextDark: const Color(0xFFC4A774),
                        ),
                        TimelineEvent(
                          hour: 11,
                          title: 'Weekly Prep',
                          time: '11:15AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 13,
                          title: 'Product Sprint',
                          time: '1PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Team Goals',
                          time: '3PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                      ],
                      tomorrowEvents: [
                        TimelineEvent(
                          hour: 9,
                          title: 'Team Goals',
                          time: '9AM',
                          color: const Color(0xFFEE4B55),
                          backgroundColorLight: const Color(0xFFFCECEC),
                          backgroundColorDark: const Color(0xFF4A1818),
                          textColorLight: const Color(0xFF5C1519),
                          textColorDark: const Color(0xFFF1A9A9),
                        ),
                        TimelineEvent(
                          hour: 10,
                          title: 'Design Review',
                          time: '10AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 14,
                          title: 'Team Lunch',
                          time: '2PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Regroup',
                          time: '3PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                        ),
                      ],
                      tomorrowSpecialEvent: SpecialEvent(
                        title: "Ravi's Birthday",
                        icon: Icons.card_giftcard,
                      ),
                      todayMoreEventsCount: 3,
                      todayMoreEventsColors: [
                        const Color(0xFFFED6A3),
                        const Color(0xFFF5B8C8),
                        const Color(0xFFA5D4F1),
                      ],
                      tomorrowMoreEventsCount: 2,
                      tomorrowMoreEventsColors: [
                        const Color(0xFFC4B5FD),
                        const Color(0xFFF9A8D4),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                _buildSectionTitle('大尺寸'),
                const SizedBox(height: 8),
                Center(
                  child: SizedBox(
                    width: 300,
                    height: 300,
                    child: TimelineScheduleCard(
                      size: const LargeSize(),
                      todayWeekday: 'Monday',
                      todayDay: 7,
                      tomorrowWeekday: 'Tuesday',
                      tomorrowDay: 8,
                      todayEvents: [
                        TimelineEvent(
                          hour: 10,
                          title: 'Farmers Market',
                          time: '9:45AM',
                          color: const Color(0xFFF3A541),
                          backgroundColorLight: const Color(0xFFFEF7EC),
                          backgroundColorDark: const Color(0xFF4A3816),
                          textColorLight: const Color(0xFF6B4916),
                          textColorDark: const Color(0xFFFFD699),
                          subtextLight: const Color(0xFFA68B4E),
                          subtextDark: const Color(0xFFC4A774),
                        ),
                        TimelineEvent(
                          hour: 11,
                          title: 'Weekly Prep',
                          time: '11:15AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 13,
                          title: 'Product Sprint',
                          time: '1PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Team Goals',
                          time: '3PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                      ],
                      tomorrowEvents: [
                        TimelineEvent(
                          hour: 9,
                          title: 'Team Goals',
                          time: '9AM',
                          color: const Color(0xFFEE4B55),
                          backgroundColorLight: const Color(0xFFFCECEC),
                          backgroundColorDark: const Color(0xFF4A1818),
                          textColorLight: const Color(0xFF5C1519),
                          textColorDark: const Color(0xFFF1A9A9),
                        ),
                        TimelineEvent(
                          hour: 10,
                          title: 'Design Review',
                          time: '10AM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                          subtextLight: const Color(0xFF5D9E33),
                          subtextDark: const Color(0xFF7DB852),
                        ),
                        TimelineEvent(
                          hour: 14,
                          title: 'Team Lunch',
                          time: '2PM',
                          color: const Color(0xFF4BA1F1),
                          backgroundColorLight: const Color(0xFFEEF7FE),
                          backgroundColorDark: const Color(0xFF1A3A5A),
                          textColorLight: const Color(0xFF1A3B5A),
                          textColorDark: const Color(0xFF9BC9F1),
                        ),
                        TimelineEvent(
                          hour: 15,
                          title: 'Regroup',
                          time: '3PM',
                          color: const Color(0xFF6BD425),
                          backgroundColorLight: const Color(0xFFEFF9E9),
                          backgroundColorDark: const Color(0xFF1D3D16),
                          textColorLight: const Color(0xFF2F5913),
                          textColorDark: const Color(0xFF9BC968),
                        ),
                      ],
                      tomorrowSpecialEvent: SpecialEvent(
                        title: "Ravi's Birthday",
                        icon: Icons.card_giftcard,
                      ),
                      todayMoreEventsCount: 3,
                      todayMoreEventsColors: [
                        const Color(0xFFFED6A3),
                        const Color(0xFFF5B8C8),
                        const Color(0xFFA5D4F1),
                      ],
                      tomorrowMoreEventsCount: 2,
                      tomorrowMoreEventsColors: [
                        const Color(0xFFC4B5FD),
                        const Color(0xFFF9A8D4),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                _buildSectionTitle('中宽尺寸'),
                const SizedBox(height: 8),
                SizedBox(
                  width: MediaQuery.of(context).size.width - 32,
                  height: 320,
                  child: TimelineScheduleCard(
                    size: const WideSize(),
                    todayWeekday: 'Monday',
                    todayDay: 7,
                    tomorrowWeekday: 'Tuesday',
                    tomorrowDay: 8,
                    todayEvents: [
                      TimelineEvent(
                        hour: 10,
                        title: 'Farmers Market - Weekly Shopping',
                        time: '9:45AM',
                        color: const Color(0xFFF3A541),
                        backgroundColorLight: const Color(0xFFFEF7EC),
                        backgroundColorDark: const Color(0xFF4A3816),
                        textColorLight: const Color(0xFF6B4916),
                        textColorDark: const Color(0xFFFFD699),
                        subtextLight: const Color(0xFFA68B4E),
                        subtextDark: const Color(0xFFC4A774),
                      ),
                      TimelineEvent(
                        hour: 11,
                        title: 'Weekly Prep Meeting',
                        time: '11:15AM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 13,
                        title: 'Product Sprint Review',
                        time: '1PM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 15,
                        title: 'Team Goals and Planning',
                        time: '3PM',
                        color: const Color(0xFF4BA1F1),
                        backgroundColorLight: const Color(0xFFEEF7FE),
                        backgroundColorDark: const Color(0xFF1A3A5A),
                        textColorLight: const Color(0xFF1A3B5A),
                        textColorDark: const Color(0xFF9BC9F1),
                      ),
                    ],
                    tomorrowEvents: [
                      TimelineEvent(
                        hour: 9,
                        title: 'Team Goals Setting',
                        time: '9AM',
                        color: const Color(0xFFEE4B55),
                        backgroundColorLight: const Color(0xFFFCECEC),
                        backgroundColorDark: const Color(0xFF4A1818),
                        textColorLight: const Color(0xFF5C1519),
                        textColorDark: const Color(0xFFF1A9A9),
                      ),
                      TimelineEvent(
                        hour: 10,
                        title: 'Design Review Session',
                        time: '10AM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 14,
                        title: 'Team Lunch Meeting',
                        time: '2PM',
                        color: const Color(0xFF4BA1F1),
                        backgroundColorLight: const Color(0xFFEEF7FE),
                        backgroundColorDark: const Color(0xFF1A3A5A),
                        textColorLight: const Color(0xFF1A3B5A),
                        textColorDark: const Color(0xFF9BC9F1),
                      ),
                      TimelineEvent(
                        hour: 15,
                        title: 'Project Regroup',
                        time: '3PM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                      ),
                    ],
                    tomorrowSpecialEvent: SpecialEvent(
                      title: "Ravi's Birthday Celebration",
                      icon: Icons.card_giftcard,
                    ),
                    todayMoreEventsCount: 3,
                    todayMoreEventsColors: [
                      const Color(0xFFFED6A3),
                      const Color(0xFFF5B8C8),
                      const Color(0xFFA5D4F1),
                    ],
                    tomorrowMoreEventsCount: 2,
                    tomorrowMoreEventsColors: [
                      const Color(0xFFC4B5FD),
                      const Color(0xFFF9A8D4),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                _buildSectionTitle('大宽尺寸'),
                const SizedBox(height: 8),
                SizedBox(
                  width: MediaQuery.of(context).size.width - 32,
                  height: 420,
                  child: TimelineScheduleCard(
                    size: const Wide2Size(),
                    todayWeekday: 'Monday',
                    todayDay: 7,
                    tomorrowWeekday: 'Tuesday',
                    tomorrowDay: 8,
                    todayEvents: [
                      TimelineEvent(
                        hour: 10,
                        title: 'Farmers Market - Weekly Shopping Trip',
                        time: '9:45AM',
                        color: const Color(0xFFF3A541),
                        backgroundColorLight: const Color(0xFFFEF7EC),
                        backgroundColorDark: const Color(0xFF4A3816),
                        textColorLight: const Color(0xFF6B4916),
                        textColorDark: const Color(0xFFFFD699),
                        subtextLight: const Color(0xFFA68B4E),
                        subtextDark: const Color(0xFFC4A774),
                      ),
                      TimelineEvent(
                        hour: 11,
                        title: 'Weekly Preparation Meeting',
                        time: '11:15AM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 13,
                        title: 'Product Sprint Review Session',
                        time: '1PM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 15,
                        title: 'Team Goals and Planning Session',
                        time: '3PM',
                        color: const Color(0xFF4BA1F1),
                        backgroundColorLight: const Color(0xFFEEF7FE),
                        backgroundColorDark: const Color(0xFF1A3A5A),
                        textColorLight: const Color(0xFF1A3B5A),
                        textColorDark: const Color(0xFF9BC9F1),
                      ),
                      TimelineEvent(
                        hour: 16,
                        title: 'Client Call - Project Update',
                        time: '4PM',
                        color: const Color(0xFF9B59B6),
                        backgroundColorLight: const Color(0xFFF5F0FE),
                        backgroundColorDark: const Color(0xFF2D1F4A),
                        textColorLight: const Color(0xFF4A2070),
                        textColorDark: const Color(0xFFD4B8F1),
                      ),
                    ],
                    tomorrowEvents: [
                      TimelineEvent(
                        hour: 9,
                        title: 'Team Goals Setting Meeting',
                        time: '9AM',
                        color: const Color(0xFFEE4B55),
                        backgroundColorLight: const Color(0xFFFCECEC),
                        backgroundColorDark: const Color(0xFF4A1818),
                        textColorLight: const Color(0xFF5C1519),
                        textColorDark: const Color(0xFFF1A9A9),
                      ),
                      TimelineEvent(
                        hour: 10,
                        title: 'Design Review and Feedback',
                        time: '10AM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                        subtextLight: const Color(0xFF5D9E33),
                        subtextDark: const Color(0xFF7DB852),
                      ),
                      TimelineEvent(
                        hour: 14,
                        title: 'Team Lunch and Networking',
                        time: '2PM',
                        color: const Color(0xFF4BA1F1),
                        backgroundColorLight: const Color(0xFFEEF7FE),
                        backgroundColorDark: const Color(0xFF1A3A5A),
                        textColorLight: const Color(0xFF1A3B5A),
                        textColorDark: const Color(0xFF9BC9F1),
                      ),
                      TimelineEvent(
                        hour: 15,
                        title: 'Project Regroup and Next Steps',
                        time: '3PM',
                        color: const Color(0xFF6BD425),
                        backgroundColorLight: const Color(0xFFEFF9E9),
                        backgroundColorDark: const Color(0xFF1D3D16),
                        textColorLight: const Color(0xFF2F5913),
                        textColorDark: const Color(0xFF9BC968),
                      ),
                    ],
                    tomorrowSpecialEvent: SpecialEvent(
                      title: "Ravi's Birthday Celebration - Special Event",
                      icon: Icons.celebration,
                    ),
                    todayMoreEventsCount: 3,
                    todayMoreEventsColors: [
                      const Color(0xFFFED6A3),
                      const Color(0xFFF5B8C8),
                      const Color(0xFFA5D4F1),
                    ],
                    tomorrowMoreEventsCount: 2,
                    tomorrowMoreEventsColors: [
                      const Color(0xFFC4B5FD),
                      const Color(0xFFF9A8D4),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w600,
        color: Colors.grey,
      ),
    );
  }
}
