name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release --no-tree-shake-icons
      
    - name: Create ZIP package
      run: |
        if (Test-Path build/windows/runner/Release) {
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath build/windows/runner/Release/Memento.zip -Force
        } else {
          Write-Error "Release directory not found at build/windows/runner/Release"
          exit 1
        }
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        files: build/windows/runner/Release/Memento.zip
        tag_name: release-${{ steps.date.outputs.date }}-${{ steps.commit_sha.outputs.sha }}
        generate_release_notes: false
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build/windows/runner/Release/