name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release --no-tree-shake-icons
      
    - name: Create ZIP package
      run: |
        $releaseDir = "build/windows/runner/Release"
        Write-Output "Checking for release directory at $releaseDir"
        
        if (-not (Test-Path $releaseDir)) {
          Write-Error "Release directory not found at $releaseDir"
          Write-Output "Contents of build/windows/runner:"
          Get-ChildItem -Path build/windows/runner -Recurse | Format-Table -AutoSize
          exit 1
        }
        
        Write-Output "Found release directory, contents:"
        Get-ChildItem -Path $releaseDir | Format-Table -AutoSize
        
        $zipPath = "$releaseDir/Memento-windows.zip"
        Write-Output "Creating ZIP package at $zipPath"
        Compress-Archive -Path "$releaseDir/*" -DestinationPath $zipPath -Force
        
        if (-not (Test-Path $zipPath)) {
          Write-Error "Failed to create ZIP package at $zipPath"
          exit 1
        }
        
        Write-Output "Successfully created ZIP package:"
        Get-Item -Path $zipPath | Format-Table -AutoSize
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        files: build/windows/runner/Release/Memento-windows.zip
        tag_name: release-${{ steps.date.outputs.date }}-${{ steps.commit_sha.outputs.sha }}
        generate_release_notes: false
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build/windows/runner/Release/