name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release --no-tree-shake-icons
      
    - name: Create ZIP package
      run: cd build/windows/runner/Release && zip -r Memento.zip ./*
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        tag_name: release-${{ steps.date.outputs.date }}-${{ steps.commit_sha.outputs.sha }}
        release_name: Release ${{ steps.date.outputs.date }} (${{ steps.commit_sha.outputs.sha }})
        draft: false
        prerelease: false
        
    - name: Upload Windows App to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/windows/runner/Release/Memento.zip
        asset_name: Memento-${{ steps.date.outputs.date }}.zip
        asset_content_type: application/zip
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build/windows/runner/Release/